### ISSUE TITLE
Invalid Index

### ISSUE THREAD

**Issue by nokieng17** [oliviertassinari/react-swipeable-views#512] opened 2019-05-24 03:55 UTC
`SwipeableView` produce `<labe>invalid index</label>`

```
  <SwipeableView
            axis="x"
            index={currentTab}
            onChangeIndex={handleIndexChanged}
            enableMouseEvents
        >
....
</SwipeableView>
```

The code above produces the `invalid index`. the parameter `currentTab` is in range [0,1,2] as the number of existing tabs.

The complete code is available on GitHub. It is my Udacity project [link]
The code is on the file `src/components/TabBook.js`
(https://github.com/KiengKnot/reactnd-project-myreads-starter)

## Environment

| Tech                   | Version |
|------------------------|---------|
| react-swipeable-views  | 0.13.3 |
| React                  |    16.8.6     |
| platform               |    browser    |
| node                    |    12.1.0     |

**Comment by caleb-harrelson** [comment] 2020-08-14 05:13
If you can put together an isolated reproduction of the problem on [codesandbox](https://codesandbox.io/s/github/oliviertassinari/react-swipeable-views/tree/master/examples/create-react-app) it would be easier to diagnose.

Due to the age of the issue I'm going to close it, but if you put an example together you can open a new issue.

**Closed by caleb-harrelson** 2020-08-14 05:13 UTC
