### ISSUE TITLE
Is this possible w editing the component?  - Swipe down lets X number of cards then when I swipe to the right, it shows the TOP of the next row 

### ISSUE THREAD

**Issue by dnecklesportfolio** [oliviertassinari/react-swipeable-views#194] opened 2016-11-23 15:10 UTC
Swipe down lets X number of cards then when I swipe to the right, it shows the TOP of the next row.

Does that make sense? This may require me to tinker with the way your component works.. hopefully not to complex

**Comment by oliviertassinari** [comment] 2016-11-24 22:54
Sorry, that doesn't make sense to me.

**Comment by dnecklesportfolio** [comment] 2016-11-24 23:46
It doesn't? 
Let me back up a bit, currently the way it works if i am in row A and I swiped down 4 cards, then i swipe to the right, i would see the 4th card of the next row( row B ). Right?


I want to change that so you see the first card in row B. This would require not moving the whole grid and just the row down... does that help.

**Comment by oliviertassinari** [comment] 2016-11-25 10:37
Well, could you provide a reproduction test case with what you are doing and where it fails? That would help a lot 👷 . http://www.webpackbin.com.

**Comment by emanuelsetitinger** [comment] 2016-11-26 07:31
Since I've already encountered the same behavior, I'm also interested in ideas on this. Please find the following reproduction test case on webpackbin:
http://www.webpackbin.com/VyDZsfMMf 
Reproduction steps:
1) scroll down to the bottom of the first slide
2) switch to slide 2
3) you end up well below the content of slide 2

Is it possible to end up at the top of slide 2 after switching?

@dnecklesportfolio I hope I didn't misunderstand your question.

**Comment by oliviertassinari** [comment] 2016-11-28 12:43
@emanuelsetitinger Thanks for the webpackbin example!
I see two options here:
1. You can use the `containerStyle` property to set a max height. E.g. http://www.webpackbin.com/Vy8VBGrMf
2. You can scroll to the top when changing index. But I think that it should be users responsibility and not the lib.

**Comment by dnecklesportfolio** [comment] 2016-11-28 12:55
@emanuelsetitinger Thanks for the webpackbin, Your example was close, but not it.  i will make a demo.

**Comment by emanuelsetitinger** [comment] 2016-11-28 20:48
Thank you for the answer! I fully agree that the options you pointed out are superior to changing the lib. This helped me a lot!

**Comment by dnecklesportfolio** [comment] 2016-11-28 21:18
@oliviertassinari If i wanted a custom version of the component how much do you charge per hour to development. I realize that you don't understand my initial ask so I will make a demo to explain..

**Comment by oliviertassinari** [comment] 2016-11-29 19:52
@dnecklesportfolio I'm not sure that I will have time to work on your specific needs.
I'm doing it for fun. Let's close this issue as I think we went down the rabbit hole 🐰 .
Thanks.

**Closed by oliviertassinari** 2016-11-29 19:52 UTC
