### ISSUE TITLE
Module not found: Can't resolve 'dom-helpers/transition/properties' in 

### ISSUE THREAD

**Issue by bouyagas** [oliviertassinari/react-swipeable-views#581] opened 2020-01-28 20:51 UTC
![image](https://user-images.githubusercontent.com/6065727/73304653-ad0fd180-41e6-11ea-8c78-d67666f7362c.png)

**Comment by wisekaa03** [comment] 2020-01-29 05:22
I tried to upgrade to 0.13.6, but this problem forced me to roll back to 0.13.3

**Comment by thclark** [comment] 2020-01-29 14:12
This is surely a duplicate of #566

**Comment by theshashiverma** [comment] 2020-01-30 07:19
@bouyagas downgrade to 0.12.18 this will work

**Comment by oliviertassinari** [comment] 2020-02-01 12:15
Duplicate of #564

**Closed by oliviertassinari** 2020-02-01 12:15 UTC
