### ISSUE TITLE
How can i stop Stop the bounce effect in ios when using this lib. 

### ISSUE THREAD

**Issue by jasan-s** [oliviertassinari/react-swipeable-views#141] opened 2016-09-11 07:15 UTC
Got it working. Thanks for making this, its pretty awesome. Since I can't set the position to absolute for the react-swipeable-views container, is there any way to stop the bouncing effect on ios?

**Comment by oliviertassinari** [comment] 2016-09-11 13:40
> I can't set the position to absolute for the react-swipeable-views container

Why can't you?

>  Is there any way to stop the bouncing effect on ios?

Where is the bouncing effect coming from? I can't reproduce it.

**Comment by oliviertassinari** [comment] 2016-09-12 20:12
@jasan-s This issue sounds linked to a wrong usage of the component. I'm closing this issue until I have a better reproduction test case. You can use this workbench as a starting point http://www.webpackbin.com/VJjMoggnZ.

**Closed by oliviertassinari** 2016-09-12 20:12 UTC
Labels: Browser
