### ISSUE TITLE
Library is using "Legacy context API"

### ISSUE THREAD

**Issue by AleTid5** [oliviertassinari/react-swipeable-views#611] opened 2020-07-16 11:14 UTC
Hi there!
I started to use this library, and when I opened the console, the only warning that I received is from here. A **Context Legacy API** is being used, which is experimental and will be deprecated in major versions of react. [Link to warning](https://reactjs.org/docs/context.html#legacy-api)
Hopefully you can fix it!

Regards!

**Comment by korbav** [comment] 2020-07-18 05:33
Same here, the full message : 

```
index.js:1 Warning: Legacy context API has been detected within a strict-mode tree.

The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.

Please update the following components: ReactSwipableView

Learn more about this warning here: https://fb.me/react-legacy-context
```

**Comment by caleb-harrelson** [comment] 2020-08-14 04:22
Duplicate of #596

**Closed by caleb-harrelson** 2020-08-14 04:22 UTC
Labels: v17 Support
