### ISSUE TITLE
Updating React to 15.4.1 brings dependency issue with this package

### ISSUE THREAD

**Issue by DennisBecker** [oliviertassinari/react-swipeable-views#197] opened 2016-11-29 14:17 UTC
Can you also release a new version which supports react-tap-event-plugin v2.0.1 ?

I want to update my dependencies for react 15.4.1 and the latest release still uses react-tap-event-plugin v1.x

**Comment by oliviertassinari** [comment] 2016-11-29 14:25
What's blocking it? I don't have any dependency to it: https://github.com/oliviertassinari/react-swipeable-views/blob/master/package.json#L34-L43.

**Comment by oliviertassinari** [comment] 2016-12-02 12:31
I'm closing this issue. I don't think that the root of the issue is here.

**Closed by oliviertassinari** 2016-12-02 12:31 UTC
