### ISSUE TITLE
All codesandbox links do not work

### ISSUE THREAD

**Issue by caihongxu** [oliviertassinari/react-swipeable-views#571] opened 2020-01-20 01:36 UTC
All codesandbox links from the demos page do not work (ModuleNotFoundError).

**Comment by jeanpoelie** [comment] 2020-01-21 06:43
Good catch, something seems to have changed on codesandbox, I will try to check it out later this week!

**Comment by oliviertassinari** [comment] 2020-02-01 12:21
Duplicate of #564

**Closed by oliviertassinari** 2020-02-01 12:21 UTC
Labels: duplicate
