### ISSUE TITLE
tab and pannel is not  same  on mobile  in demo2 

### ISSUE THREAD

**Issue by sunny628** [oliviertassinari/react-swipeable-views#361] opened 2017-10-31 09:04 UTC
http://oliviertassinari.github.io/react-swipeable-views/
![tim 20171031170027](https://user-images.githubusercontent.com/16478878/32215551-3b4600ba-be5d-11e7-9571-e1eba04dfd20.png)

in demo2  when switch the pannel   ,the  tab  is not change,
is there any way to resolve ?

**Comment by oliviertassinari** [comment] 2017-10-31 09:35
I'm closing as a duplicate of #358.

**Closed by oliviertassinari** 2017-10-31 09:35 UTC
Labels: duplicate
