### ISSUE TITLE
First swipe doesn't animate when view contains MUI Select

### ISSUE THREAD

**Issue by Edistra** [oliviertassinari/react-swipeable-views#417] opened 2018-02-27 04:33 UTC
If one of my views contains a MUI Select, the first swipe does not animate.

I don't know what causes this behaviour in this particular component, but for now it's the only one I've seen doing that.

![awesomescreenshot-2018-02-27t04-24-01-571z 1](https://user-images.githubusercontent.com/13304634/36710627-2b1ff25c-1b4d-11e8-834e-d34e1fa1083a.gif)

I made a repo to reproduce the issue : https://github.com/Edistra/react-swipeable-views-issue

**Comment by sebastianvoss** [comment] 2018-03-09 13:28
Same issue here (even without having a MUI select in the view). Reverting back to `v0.12.4` solves the issue.

**Comment by oliviertassinari** [comment] 2018-03-18 19:01
The root of the issue is on Material-UI side. I'm closing for https://github.com/mui-org/material-ui/issues/10643.

**Closed by oliviertassinari** 2018-03-18 19:01 UTC
