### ISSUE TITLE
[SwipeableViews] {state: heightLatest} is not adjusting

### ISSUE THREAD

**Issue by vans163** [oliviertassinari/react-swipeable-views#36] opened 2016-02-26 02:53 UTC
heightLatest which determines whether to display a scrollbar for the SwipeableViews is not adjusting dynamically when the size of the content on the page changes. For example if you refresh the page and it inits with with a heightLatest of 200, when you open a 600px size dropdown, the dropdown will get cut off and a scrollbar will appear.

I propose to add an option to set a max/default heightLatest, or to fix the behavior to automatically adjust if something inside the SwipeableView needs more space.

**Comment by oliviertassinari** [comment] 2016-02-27 11:38
> For example if you refresh the page and it inits with with a heightLatest of 200, when you open a 600px size dropdown, the dropdown will get cut off and a scrollbar will appear.

One way to fix it is to have the root of the drop-down outside of the `SwipeableView`. That's how an html `<select />` is working and how the `<SelectField />` of Material-UI work.

> I propose to add an option to set a max/default heightLatest, or to fix the behavior to automatically adjust if something inside the SwipeableView needs more space.

I'm open to a PR. Maybe using the style `minHeight` instead of `height` will do the trick.

**Comment by vans163** [comment] 2016-02-27 15:01
Im not sure what you mean. What does having the root of the drop-down outside the swipableview mean?  
<SwipeableViews /> just alone by itself like this, with the tab contents below it?

Because if say I expand a dropdown, the heightLatest stays fixed, but if I swipe it left and right the heightLatest correctly adjusts.  Why not just have the SwipableView adjust its heightLatest whenever a statechange occurs from a child of it (instead of only adjusting it after a left/right swipe). Not sure if this is correct new to react.

For now I just decided to stop using material UI, too many things don't work how I want and I

**Comment by jgauthie** [comment] 2016-03-01 19:43
Hi, having the same issue with height.

I'm using SwipeableViews a lot, thx for your module by the way !
This problem happens a lot when you have dynamic content.

For example, a new chat message, if the conversation is in a swipeable block, won't appear automaticaly in this block if I don't force overflowY with a fixedHeight.

Is it possible to force motionStyle over some conditions (height: 'auto' instead of calculatedHeight for example) for specifics swipeable content ?

**Comment by Gaubee** [comment] 2016-03-04 07:10
@vans163  I have the same needs.
when ChangeIndex , SwipeableViews recalculated height.
Therefore, through this feature, you can do like this:
```js

  changeTabIndex(index_value){
      this.setState({
          ...this.state,
          index_value
      });
  }
```
```html
<SwipeableViews onChangeIndex={::this.changeTabIndex} index={this.state.index_value}>
  <div onClick={()=>this.changeTabIndex(0)}>
```

**Comment by amangeot** [comment] 2016-05-13 17:16
Hello,
I am having the same issues dynamically loading a mosaic of images. 

The page loads first, and then images. The problem is that the SwipeableViews is first loaded "minimized" and won't update its height after images have downloaded. So images are displayed in a small scrollable area.

Has anybody solved this problem ? @vans163 ?

I'd love to be able to use this module, it looks amazing!

**Comment by oliviertassinari** [comment] 2016-05-13 17:59
@amangeot One work around would be to wait for the image to be loaded before mounting the `SwipeableViews`.

**Comment by patotoma** [comment] 2016-08-05 13:23
this should be labeled as bug and should be fixed

until then as a workaround setting
`height: auto;`
to wrapper element will do the trick

**Comment by oliviertassinari** [comment] 2016-08-05 17:34
@patotoma Do you have another example where the height adjustement is not working?

> this should be labeled as bug and should be fixed

I see two options:
1. We could defer the height measurment to when we actually need it. I mean, when we are transitioning between slides. I think that we would address the majority of our issues. Still not a 100% resilient approach.
2. We make this feature optional as is having two drawbacks:
 - Isn't working in 100% of our casses
 - Reduce performances

**Comment by oliviertassinari** [comment] 2016-08-05 17:35
What do you guys prefer?

**Comment by Zetberg** [comment] 2016-08-19 15:50
+1
same issue, I have tables with collapsed rows which expand on button click

**Comment by oliviertassinari** [comment] 2016-08-20 22:04
I went with option 2.

**Closed** 2016-08-20 22:03 UTC
Labels: bug
