### ISSUE TITLE
componentWillMount should be renamed to componentDidMount

### ISSUE THREAD

**Issue by H3JFC** [oliviertassinari/react-swipeable-views#624] opened 2020-09-14 17:23 UTC
I'm getting the following error 
```Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move code from componentWillMount to componentDidMount (preferred in most cases) or the constructor.
```
FYI: Am not sure how this would affect backward compatibility

- [x] I have searched the [issues](https://github.com/oliviertassinari/react-swipeable-views/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
There should be no warning

## Current Behavior
There is a warning

## Steps to Reproduce (for bugs)
Use any of the components with "componentWillMount" with the environments below

## Context
Not a priority, but it's a nice-to-have and probably a quick fix

## Your Environment

| Tech                   | Version |
|------------------------|---------|
| react-swipeable-views  |   0.13.9     |
| React                  |    16.13.1     |
| Next             |     9.3.6    |

**Comment by caleb-harrelson** [comment] 2020-09-18 15:04
Duplicate of #597

**Closed by caleb-harrelson** 2020-09-18 15:04 UTC
