### ISSUE TITLE
Loop on all the slides

### ISSUE THREAD

**Issue by MattKetmo** [oliviertassinari/react-swipeable-views#294] opened 2017-05-19 12:49 UTC
Hello,
I'd like to suggest a new feature: ability to create a loop with all the slides so you can swipe indefinitely, it will take the elements from the beginning (or from the end, depending on the direction).
An example of something similar I'm trying to build is the carrousel at http://google.ai/ (below "Our Vision") where you can partially see the previous and the next slide of current one.

**Comment by oliviertassinari** [comment] 2017-05-19 13:11
Hey, I believe that this issue is a duplicate of #181.

**Comment by oliviertassinari** [comment] 2017-05-19 13:13
It can be implemented as we are speaking, but the API could be improved. I would love your feedback on that point.

**Closed by oliviertassinari** 2017-05-19 13:13 UTC
Labels: duplicate
