### ISSUE TITLE
Can't resolve 'animated/lib/targets/react-dom'

### ISSUE THREAD

**Issue by shinescy** [oliviertassinari/react-swipeable-views#568] opened 2020-01-16 18:46 UTC
I get this error in  react-swipeable-views: 0.13.4  version
AND
"@material-ui/core": "^4.8.0",
    "@material-ui/icons": "^4.5.1",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",

import Animated from 'animated/lib/targets/react-dom

I check react-swipeable-views/package.json compare myproject package.json 

It is missing ”animated": "^0.2.1" ？

**Comment by shinescy** [comment] 2020-01-16 18:48
when i copy  "Custom display with a coverflow effect " code and run it.
 catch this error

**Comment by shinescy** [comment] 2020-01-16 18:52
oh~!  i install the animated 0.2.2 and then catch this:Can't resolve 'dom-helpers/events/off' #567

**Comment by oliviertassinari** [comment] 2020-02-01 12:22
Duplicate of #564

**Closed by oliviertassinari** 2020-02-01 12:22 UTC
