### ISSUE TITLE
Updating the version from 0.13.3 to 0.13.5 caused the error in console

### ISSUE THREAD

**Issue by shafaqkazmi** [oliviertassinari/react-swipeable-views#576] opened 2020-01-22 15:23 UTC
Updating the version from `0.13.3` to `0.13.5` caused the below error in console:
```
index.js:1 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

react-dom.development.js:26629 Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
```

- [x] I have searched the [issues](https://github.com/oliviertassinari/react-swipeable-views/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

Everything should be working fine after version update.
## Current Behavior

There is a JS error and code is break.
## Steps to Reproduce (for bugs)

1. Update the version from `0.13.3` to `0.13.5`
2. Run the application
3. Error in console

```
<Tabs
        value={tabIndex}
        onChange={onTabChange}
        indicatorColor={colors.primary}
        textColor={colors.primary}
      >
        {items.map(({ label, id, count = 0 }) => (
          <Tab key={id} label={`${t(label)} (${count})`} />
        ))}
      </Tabs>
      <SwipeableViews index={tabIndex} onChangeIndex={updateTabIndex}>
        <div>Tab 1</div>
        <div>Tab 2</div>
        <div>Tab 3</div>
      </SwipeableViews>
```
## Your Environment

| Tech                   | Version |
|------------------------|---------|
| react-swipeable-views  |^0.13.5    |
| React                  | ^16.12.0     |
| platform               |         |
| etc                    |         |

**Comment by jeanpoelie** [comment] 2020-01-22 20:43
Unfortunatly i still need to experience my first successfull build/publish using the pre-made commands by the owner.

Currently I run into issues like so:

> ```
lerna notice cli v3.20.2
lerna info Executing command in 3 packages: "babel --config-file ../../babel.config.js src --out-dir lib --ignore test.js"
src/checkIndexBounds.js -> lib/checkIndexBounds.js
src/computeIndex.js -> lib/computeIndex.js
src/constant.js -> lib/constant.js
src/getDisplaySameSlide.js -> lib/getDisplaySameSlide.js
src/index.js -> lib/index.js
src/mod.js -> lib/mod.js
SyntaxError: src/autoPlay.js: Unexpected token (9:10)
   7 | export default function autoPlay(MyComponent) {
   8 |   class AutoPlay extends React.Component {
>  9 |     timer = null;
     |           ^
  10 | 
  11 |     constructor(props) {
  12 |       super(props);
```

**Comment by baoduy** [comment] 2020-01-23 13:39
I'm facing the same issue. The package is not stable from v0.13.1 onward.

**Comment by iamhimadri** [comment] 2020-01-23 13:47
Same issue with v0.13.5 as mentioned by @shafaqkazmi, I had to downgrade to v0.13.3 to make it work.

**Comment by divyanshukr96** [comment] 2020-01-23 14:34
these issue is caused by the whole source package is uploaded to the [NPM](https://www.npmjs.com/package/react-swipeable-views).

**Comment by Rykuno** [comment] 2020-01-24 01:09
Same issue here. 

`react-dom.development.js:57 Uncaught (in promise) Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.`

Version 13.5

**Comment by theshashiverma** [comment] 2020-01-24 12:03
@iamhimadri  doesn't work with 0.13.3

**Comment by theshashiverma** [comment] 2020-01-24 12:24
![image](https://user-images.githubusercontent.com/43005725/73068944-7ed27f00-3ed2-11ea-8189-22f773c34ea4.png)


I am getting this in my console, If I remove the swipeable from file it works fine..why?

**Comment by shafaqkazmi** [comment] 2020-01-24 12:26
@theshashiverma:  this problem is with the latest version. Please downgrade the version to `0.13.3`

**Comment by petercutting** [comment] 2020-01-24 13:22
I have the same issue. 0.13.3 works OK but get error with 0.13.5 and 0.13.5-rc. (0.13.4 also works OK)

error is - backend.js:6 Warning: React.createElement: type is invalid -- expected a string ...

downgrade with:-
npm install  --save react-swipeable-views@0.13.3

my goal is to nicely handle views with very different heights.

**Comment by pandaiolo** [comment] 2020-01-24 14:56
I'm fine with `0.13.14`, not above. I also was abused by the `latest` tag on the rc... no big deal I downgraded. Thanks for your efforts @jeanpoelie

**Comment by giuliogallerini** [comment] 2020-01-24 14:58
> 0.13.3

Works properly as component although it seems like the package hasn't been compiled correctly and it creates an issue (error message below 👇) when running the tests using jest.

```javascript
/Users/giuliogallerini/Code/Appical/cam-frontend-web/node_modules/react-swipeable-views-core/lib/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export { default as checkIndexBounds } from './checkIndexBounds';
```

As a **temporary** fix in our project we set up a mock for `react-swipeable-views` to avoid this error. Here is the mock for you to use:

```javascript
jest.mock("react-swipeable-views-core", () => ({
    __esModule: true,
    default: ({ children }) => children,
}))
```

Thank you @jeanpoelie and the other contributors for the effort you are putting on this. It's much appreciated!

**Comment by theshashiverma** [comment] 2020-01-27 04:52
I downgraded it to 0.12.18, although it's 1 year old,  it started working on my machine.

**Comment by theshashiverma** [comment] 2020-01-28 03:19
Did anyone get issues with dom-helpers of react-bootstrap with this package?

**Comment by jeanpoelie** [comment] 2020-01-28 05:13
> I downgraded it to 0.12.18, although it's 1 year old, it started working on my machine.

0.13.3 is the last working version, unfortunatly there were some package releasing issues which are fixed now, i am looking to rollback some issues to fix the DOM issues

**Comment by jakeleventhal** [comment] 2020-01-28 06:21
Seeing this issue as well

**Comment by jeanpoelie** [comment] 2020-01-28 06:46
To fix all these issues ill be releasing a 0.13.7 based on the latest working version (0.13.3).
Ill be than trying to figure out what pr broke the release and roll that pr back.
After that ill release a new version

Expect 0.13.7 within a few hours

**Comment by gabrielhof** [comment] 2020-01-28 17:07
It seems that this is not happening on version 0.13.6. Can someone else confirm?

**Comment by jakeleventhal** [comment] 2020-01-28 17:26
I was seeing this on 13.6

**Closed** 2020-02-01 12:17 UTC
