### ISSUE TITLE
Touch gestures not working in Edge (running on Surface Pro 4)

### ISSUE THREAD

**Issue by simonwatt** [oliviertassinari/react-swipeable-views#198] opened 2016-12-01 22:59 UTC
I'm using the component inside a UWP (Universal Windows Platform) JavaScript App, which is running on a Surface Pro 4 (which is a touch enabled device). When I swipe the tabs they don't respond to touch gestures and nothing happens.

I believe it's related to the same problem which is stopping the component working for me in Edge. I can reproduce on the demo page in browser on the Surface Pro 4:

http://oliviertassinari.github.io/react-swipeable-views/ 

Demo 2, Chrome, on Surface Pro 4. Works correctly when I swipe on the tabs.
Demo 2, Edge, on Surface Pro 4. Nothing happens when I swipe on the tabs.

I've tried various combinations of playing around with 'touch-action' in the CSS, with no success (although if i put 'touch-action: cross-slide-x' on the tab content they move a tiny bit when swiped). https://msdn.microsoft.com/en-us/library/hh772044(v=vs.85).aspx

**Comment by oliviertassinari** [comment] 2016-12-03 17:16
Thanks for raising this issue. I believe that it's a duplicate of #164.
Let's move the conversation there.

**Closed by oliviertassinari** 2016-12-03 17:16 UTC
Labels: Browser, duplicate
