### ISSUE TITLE
Peer dependency for React 16

### ISSUE THREAD

**Issue by mcqj** [oliviertassinari/react-swipeable-views#657] opened 2022-01-05 16:25 UTC
There is a dependency in react-swipeable-views-utils on react-event-listener. react-event-listener has been archived and has a peer dependency on react@^16.3.0. This leads to warnings when installing. I have not encountered runtime errors as a result.

At some stage, react-event-listener should be replaced, unless it can be unarchived to update its peer dependency.

**Comment by oliviertassinari** [comment] 2022-09-08 09:39
Duplicate of #663

**Closed by oliviertassinari** 2022-09-08 09:39 UTC
