### ISSUE TITLE
Will not install with react 18.2.0

### ISSUE THREAD

**Issue by AdamPhasey** [oliviertassinari/react-swipeable-views#672] opened 2022-08-23 16:44 UTC
Tried to install but will not accept 18.2.0. Do you have plans to upgrade its compatibility?

- [x] I have searched the [issues](https://github.com/oliviertassinari/react-swipeable-views/issues) of this repository and believe that this is not a duplicate.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech                   | Version |
|------------------------|---------|
| react-swipeable-views  |         |
| React                  |         |
| platform               |         |
| etc                    |         |

**Comment by askunlimited** [comment] 2022-08-24 07:16
having the same issue trying to install on react 18.2.0 but giving could not resolve dependency error. Is there a hack or a compatibility upgrade in sight?

**Comment by nnmax** [comment] 2022-08-24 08:56
same issue

**Comment by tahola** [comment] 2022-08-27 11:32
up, same here

**Comment by tahola** [comment] 2022-08-27 11:47
Same issue, I added a --force to npm, it seem to work fine...

`npm install --force --save react-swipeable-views`

**Comment by oliviertassinari** [comment] 2022-09-08 09:39
Duplicate of #663

**Closed by oliviertassinari** 2022-09-08 09:39 UTC
