### ISSUE TITLE
Unknown prop `disableLazyLoading` on <div> tag. Remove this prop from the element

### ISSUE THREAD

**Issue by rizkiandrianto** [oliviertassinari/react-swipeable-views#310] opened 2017-07-21 11:06 UTC
I try to update, but why I got this?

**Comment by oliviertassinari** [comment] 2017-07-21 11:24
No clue :/

**Comment by rizkiandrianto** [comment] 2017-07-21 15:24
well, trying to reproduce your sample code will cause this too in my case.
is the react version (or other depedencies) will affect this?

**Comment by oliviertassinari** [comment] 2017-07-21 22:33
I'm closing as I'm not able to reproduce on the demo/documentation.

**Closed by oliviertassinari** 2017-07-21 22:33 UTC
